import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { signIn } from 'next-auth/react'
import Loginbtn from './components/loginBtn'
import Navbar from './components/navBar'
import { getSession } from 'next-auth/react'
import { executeQuery } from "../../lib/db"
import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'

const mySchedule = [
  { title: 'Shift from 8:00-16:00 department: Cashier', date: '2023-04-01' },
  { title: 'Shift from 16:00-22:00 department: Cashier', date: '2023-04-04' },
  { title: 'Shift from 16:00-22:00 department: Floor', date: '2023-04-07' },
  { title: 'Shift from 8:00-16:00 department: Fruit & Green', date: '2023-04-08' },
  { title: 'Shift from 16:00-22:00 department: Floor', date: '2023-04-10' },
  { title: 'Shift from 8:00-16:00 department: Fruit & Green', date: '2023-04-15' },
  { title: 'Shift from 16:00-22:00 department: Fruit & Green', date: '2023-04-18' },
  { title: 'Shift from 8:00-16:00 department: Floor', date: '2023-04-23' },
  { title: 'Shift from 8:00-16:00 department: Cashier', date: '2023-04-27' },
  { title: 'Shift from 16:00-22:00 department: Floor', date: '2023-04-30' },
]

export async function getServerSideProps(ctx) {

  const session = await getSession(ctx);

  if (session) {
      // Fetch data from database
      const result = await executeQuery({
          query: 'SELECT * FROM users WHERE username = ?',
          value: [session.user.name]
      })

      // Pass data to the page via props
      console.log(result)

      return {
          props: {
              result: result,
          },
      }
  } else {
    return {
      props: {
        result: null,
      },
    }
  }
}

export default function Home({ result }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar initials={result[0].initials} name={result[0].name} />
      <div className={styles.main}>
        <div className={styles.calendar}>
          <FullCalendar
            plugins={[dayGridPlugin]}
            initialView="dayGridMonth"
            height={"100%"}
            events={mySchedule}
            eventClassNames={styles.event}
            dayHeaderFormat={{ weekday: 'long' }}
          />
        </div>
      </div>
    </>
  )
}
