import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { signIn } from 'next-auth/react'
import Loginbtn from './components/loginBtn'
import Navbar from './components/navBar'
import { getSession } from 'next-auth/react'
import { executeQuery } from "../../lib/db"

import FullCalendar from '@fullcalendar/react' // must go before plugins
import dayGridPlugin from '@fullcalendar/daygrid' // a plugin!
import timeGridPlugin from '@fullcalendar/timegrid' // a plugin!

export async function getServerSideProps(ctx) {

  const session = await getSession(ctx);

  if (session) {
      // Fetch data from database
      const result = await executeQuery({
          query: 'SELECT * FROM users WHERE username = ?',
          value: [session.user.name]
      })

      // Pass data to the page via props
      console.log(result)

      return {
          props: {
              result: result,
          },
      }
  } else {
    return {
      props: {
        result: null,
      },
    }
  }
}

export default function Home({ result }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar initials={result[0].initials} />
      <div className={styles.main}>
        <div className={styles.calendar}>
          <FullCalendar
            plugins={[timeGridPlugin]}
            initialView="timeGridWeek"
            events={[
              { title: 'event 1', date: '2023-04-13' },
              { title: 'event 2', date: '2023-04-20' }
            ]}
          />
        </div>
      </div>
    </>
  )
}
