import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Login.module.css'

export default function Login() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.title}>
                    Login Page
                </div>
            </main>
        </>
    )
}