import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { signIn } from 'next-auth/react'
import Loginbtn from './components/loginBtn'
import Navbar from './components/navBar'
import { getSession } from 'next-auth/react'
import { executeQuery } from "../../lib/db"
import WeekGridTable from './components/weekGridTable'

export async function getServerSideProps(ctx) {

  	const session = await getSession(ctx);

  	if (session) {
      	// Fetch data from database
		const result = await executeQuery({
			query: 'SELECT * FROM users WHERE username = ?',
			value: [session.user.name]
		})

      	// Pass data to the page via props

		const userSchedule = await executeQuery({
			query: 'SELECT * FROM schedule',
			value: []
		}) 

		const shiftName = await executeQuery({
			query: 'SELECT * FROM shifts',
			value: []
		})

		const users = await executeQuery({
			query: 'SELECT * FROM users',
			value: []
		})
	  
		return {
			props: {
				result: result,
				userSchedule: userSchedule,
				shiftName: shiftName,
				users: users,
			},
		}
	} else {
		return {
			props: {
				result: null,
				userSchedule: null,
				shiftName: null,
				users: null,
			},
		}
	}
}

export default function Home({ result, userSchedule, shiftName, users }) {

	
  return (
    <>
      <Head>
        <title>My Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar name={result[0].name} />
      <div className={styles.main}>
        <h1>Your Upcoming Shifts</h1>
        <div className={styles.calendar}>
          <WeekGridTable schedule={userSchedule} shiftName={shiftName} users={users} />

          
        </div>
      </div> 
    </>
  )
}
